### PR TITLE
PPE42 compare immediate branch with immediate value out of range

### PR DESCRIPTION
**Pull request by dgilbert999**

### CODE REVIEW

**Comment by dgilbert999** [comment]
These need to be sqashed into one commit.

**Comment by williamspatrick** [comment]
@dgilbert999 - So you're going to do that, right?

**Comment by dgilbert999** [comment]
Do I have sufficient authority to merge this?

**Comment by williamspatrick** [comment]
No. You need to fix up the pull request. I don't do the squash for you.

**Comment by dgilbert999** [comment]
This is ready.

**Pull request merged**
